# Generated by Django 3.2.25 on 2024-05-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFname', models.TextField(blank=True, null=True)),
                ('customerLname', models.TextField(blank=True, null=True)),
                ('sutomerAddress', models.TextField(blank=True, null=True)),
                ('customerNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='record_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('toal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
