# Generated by Django 3.2.25 on 2024-05-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_customer_record_sale'),
    ]

operations = [
    migrations.RenameModel(
        old_name='blog_product',
        new_name='product',
    ),
]
